### ISSUE TITLE
Some experimental brushes cannot be erased. 

### ISSUE THREAD

**Issue by PerlinWarp** [icosa-gallery/open-brush#10]
CandyCane, Snowflake, Holiday Tree brushes have been reported to be unerasable.

As pointed out by @dubois , CandyCane, Snowflake, Holiday Tree, and Plait brushes are all derived from ParentBrush, which does not have batching enabled and therefore they all appear as separate objects in the inspector. 
There is a comment addressing this problem [here](https://github.com/googlevr/tilt-brush/blob/c5fb8671934fe4f164ce315c675367d46267b1b5/Assets/Scripts/Brushes/ParentBrush.cs).

**Comment by andybak** [comment]
We've decided to move working experimental brushes to the main release and hide the really broken ones entirely. At some point in future someone might want to fix the 4 funky brushes but at the moment they just cause problems.
