### ISSUE TITLE
Investigate Steam support under Unity XR plug-in framework

### ISSUE THREAD

**Issue by billyquith** [icosa-gallery/open-brush#130]
* This [article](https://skarredghost.com/2020/09/25/steamvr-unity-xr-interaction-toolkit-input/) summarises the Valve OpenXR / Unity XR issue.
* [Valve's statement](https://store.steampowered.com/news/app/250820/view/2522527900755718763).
* [Unity-xr-plugin](https://github.com/ValveSoftware/unity-xr-plugin) which [does not support the Unity XR Input system](https://github.com/ValveSoftware/unity-xr-plugin/issues/16).
* Complication for issue #129.

* OpenBrush 0.3 on [SteamVR Unity Plugin](https://github.com/ValveSoftware/steamvr_unity_plugin) 2.3.2. 
* Version 2.7.3 is available and includes "support for Unity XR API" (added in 2.6.x).
* OpenVR Unity XR Plugin also available!
  * The purpose of this package is to provide OpenVR rendering to Unity XR. This package provides the necessary sdk libraries for users to build Applications that work with the OpenVR runtime. The OpenVR XR Plugin gives you access to rendering on all major VR devices through one interface. Explicit support for: HTC Vive, HTC Vive Cosmos, Oculus Rift, Oculus Rift S, Oculus Quest (Link), Windows Mixed Reality, and Valve Index. Other SteamVR compatible devices are supported though may have inaccurate or incomplete features.
  * [Valve have abandoned this plugin](https://github.com/ValveSoftware/unity-xr-plugin/issues/16#issuecomment-662708512).

It appears that Valve's direction here is: we'll support OpenXR and everyone else should follow this. 

Unity have the new Unity XR plugin system so some vendors have plugins for this, and others will be supported through the new Unity OpenXR XR plugin (requires Unity 2020.3).

**Comment by mikeskydev** [comment]
The SteamVR runtime apparently now [supports the OpenXR spec](https://store.steampowered.com/news/app/250820/view/3044967019267211914). This might mean we can use the generic OpenXR plugin with no issues, but still needs investigating.

**Comment by billyquith** [comment]
Unity are supplying a Unity XR OpenXR plug-in, which may solve these issues. [Announcement](https://forum.unity.com/threads/unity-support-for-openxr-in-preview.1023613/).

**Comment by billyquith** [comment]
There are public solutions.

> Maybe this API will solve your issue? https://github.com/VRStudios/Unity3D-XRInput
> 
> * I added a Universal bindings actions json file to XRInput (works with Index, HTC, WMR, WMR_G2 & Oculus).
> * Uses OpenVR's Input API directly instead of going through the plugin (which isn't needed). So if you're only using the legacy SteamVR SDK for input, you could remove it and use XRInput instead if it solves your problem.
> * Supports OpenXR.
> * Supports Unity's agnostic input layer (good for OVR etc).
>
> There are some oddities in in each input API which I've dealt with in the XRInput abstraction to a large degree.

**Comment by billyquith** [comment]
> The SteamVR runtime apparently now [supports the OpenXR spec](https://store.steampowered.com/news/app/250820/view/3044967019267211914). This might mean we can use the generic OpenXR plugin with no issues, but still needs investigating.

The idea was to collapse down to one SDK, i.e. the new plug-in system. We could simplify a lot of code this way. This might be a little idealistic, but the above solutions could make this happen. The Unity XR OpenXR plug-in would be layering the new Unity API on top of OpenXR, and the second solution is a wrapping abstraction for the current problem. 

Hopefully we're just in a transition period and things will settle down in the next few months and we can use the Unity OpenXR solution. This would also mean we could use vendors direct Unity XR plugins as well (which may be more reliable whilst OpenXR is in flux). We'd only need this for Steam. All the other vendors have plug-ins.

**Comment by billyquith** [comment]
Another public solution from [beep2bleep](https://github.com/beep2bleep/SteamVRWorkingWithUnityXTToolkit).

**Comment by billyquith** [comment]
The [Vive Wave XR Plugin](https://developer.vive.com/resources/vive-wave/sdk/400/vive-wave-xr-plugin/) supports new Unity XR plugin framework.

**Comment by billyquith** [comment]
Related to #222
