### ISSUE TITLE
Move to Unity 2020.x

### ISSUE THREAD

**Issue by billyquith** [icosa-gallery/open-brush#135]
As of June 2020 OpenBrush is on Unity 2019.4 LTS. It would be preferable to upgrade to 2020.3 because we could get the Unity OpenXR XR plugin. This change may mean that the SteamVR SDK is no longer required.

There may be a considerable amount of work in this change because the `UnityEngine.VR` namespace (which is currently deprecated) has been removed.

Branch for this: [feature/unity2020](https://github.com/icosa-gallery/open-brush/tree/feature/unity2020).

**Comment by merulaxr** [comment]
Now upgraded to 2021 LTS during XR integration work
