### ISSUE TITLE
Replace GvrAudioSource

### ISSUE THREAD

**Issue by billyquith** [icosa-gallery/open-brush#185]
`GvrAudioSource` is [apparently obsolete](https://forum.unity.com/threads/gvraudiosource-is-obsolete-please-upgrade-to-resonance-audio.691837/). The Google replacement is [Resonance](https://github.com/resonance-audio/resonance-audio-unity-sdk). 

This work may be required for #135, move to Unity 2020.

**Comment by merulaxr** [comment]
Resonance is also unmaintained, there may be other solutions. I don't think it's required to move to XR though!

**Comment by billyquith** [comment]
> Resonance is also unmaintained, there may be other solutions. I don't think it's required to move to XR though!

I don't think so. I put a lot of these issues up here for visibility and feedback. 

I believe audio may be included in OpenXR at some stage. I think Oculus have extensions already.

**Comment by mikeskydev** [comment]
https://github.com/ValveSoftware/steam-audio is now open source, and notably supports android and iOS. may be worth taking for a spin.
