### ISSUE TITLE
[feature/xr-plugin] Monoscopic mode height is wrong

### ISSUE THREAD

**Issue by andybak** [icosa-gallery/open-brush#188]
Camera is way higher than it normally would be.

**Comment by mikeskydev** [comment]
@andybak is this 'fixed'?

**Comment by andybak** [comment]
It seems to be. Just tested on latest commit to main.

**Comment by mikeskydev** [comment]
Thanks! I figured it was about right but I wasn't sure if it was functioning as mono used to.
