### ISSUE TITLE
Add multi-language support?

### ISSUE THREAD

**Issue by Sonic853** [icosa-gallery/open-brush#221]

**Comment by mikeskydev** [comment]
Definitely something we'd like to do! There's very little text in Open Brush, but on the flipside that also means it shouldn't be too hard to set up localization.

Relevant packages:
https://docs.unity3d.com/Packages/com.unity.localization@1.0/manual/index.html

**Comment by merulaxr** [comment]
@Sonic853 just to let you know I'm starting work on this shortly thanks to a corporate sponsor, and translations will include Chinese. Thanks for the suggestion!

**Comment by mikeage** [comment]
Let me know when there's a basic implementation, and I'll add a rough Hebrew translation (this will help confirm that RTL works)

**Comment by merulaxr** [comment]
Yermak#7594 on Discord has offered to add Russian translations when ready!

**Comment by wikieden** [comment]
Is anyone working on Chinese version?

**Comment by merulaxr** [comment]
@wikieden yes, Chinese is part of the languages we're getting translated officially!

**Comment by PGSCOM** [comment]
If you need it, I can translate to the Spanish version

**Comment by mikeskydev** [comment]
@PGSCOM thanks! While the initial set of Spanish translations are being provided by Pico (#419), once that is shipped we'll be relying on community support to get everything translated!

**Comment by mikeskydev** [comment]
The base support for this feature is now merged! We have some extras and bugfixes to do (see #429), but when we officially release this look out for details on how you can help with community translations. Thank you everyone!
