### ISSUE TITLE
Fix xr_v2 OpenXR Android

### ISSUE THREAD

**Issue by billyquith** [icosa-gallery/open-brush#222]
The `xr_v2` branch has a broken Android build. Notes on fixing.

The build appears to compile and link without error. It can be installed on a device but there appears to be no launch activity, so it it just hangs on the loading screen. The expected activity is `com.unity3d.player.UnityPlayerActivity `.

**Comment by billyquith** [comment]
If we use the AndroidManifest.xml in plugins/Android (player project override) we can build and install our Android package, but it won't launch. This appears to be because the main activity has not launch intent.

If we untick the project override, and let Unity automatically make a manifest we get a compilation error. GoogleVR appears to conflicting with the Unity generated manifest. The keyboard properties conflict.

Note: Currently GoogleVR is what is used for all of the default audio (I think, regardless of the platform).

**Comment by billyquith** [comment]
I'm using my Unity adb wrapper `uadb` to help debug this. Using Cygwin on Windows. https://github.com/billyquith/bash_common

**Comment by billyquith** [comment]
OpenXR Android requires ARM64, which requires IL2CPP. ARM64 is broken because of some assemblies that don't support it, e.g. NewtonSoft JSON, and PNGCs. - See #209. We can update the above assemblies to fix this problem. 

The problem then becomes building ARM64. There currently issues with Gradle. 
![image](https://user-images.githubusercontent.com/1754471/153780905-754338ff-0bc0-4897-ad37-04b73cc47d1a.png)

This may mean we have to have a custom Gradle config.

**Comment by billyquith** [comment]
With GoogleVR removed, the GvrAudioSource is removed. This has been renamed (temporarily?) to the Unity AudioSource. 

OpenXR has audio on the way.: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_OCULUS_audio_device_guid

**Comment by mikeskydev** [comment]
gvr code was partially restored in 53c2cf2f299a6f7733fa2486e80b641f17179b22 and select classes removed in d43bb152dad92b504ad97e0737572251b975a678

Also making a note of the warnings generated by switching to unity's internal newtonsoft JSON:
![image](https://user-images.githubusercontent.com/9121007/154573497-abad93ac-51c1-490e-a269-ffad9347c0ca.png)

**Comment by mikeskydev** [comment]
Noting that we've changed over to IL2CPP during this process but we have noted issues that were previously reverted: #209 

Updated with new data: https://github.com/icosa-gallery/open-brush/issues/209#issuecomment-1043489384

**Comment by billyquith** [comment]
We currently have a lack of consistency. Mike can run on Android but I get a black screen. Still getting silent problems, removing all of GVR doesn't work so there must be something in there being used, but if you remove it there are no warnings or errors at compilation or runtime. Or at least, nothing that looks relevant. Mike is on 2020.3.27. I am on 2020.3.22. I will update to see if there are Unity Android changes, that perhaps make a difference.

**Comment by billyquith** [comment]
Editor version contains error:
```
TypeLoadException: Could not find method due to a type load error
TiltBrush.MasterBrush..ctor () (at Assets/Scripts/Brushes/MasterBrush.cs:103)
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance[T] () (at <695d1cc93cca45069c528c15c9fdd749>:0)
TiltBrush.Pool`1[T].Get () (at Assets/Scripts/Util/Pool.cs:70)
TiltBrush.QuadStripBrush.InitBrush (TiltBrush.BrushDescriptor desc, TiltBrush.TrTransform localPointerXf) (at Assets/Scripts/Brushes/QuadStripBrush.cs:166)
TiltBrush.QuadStripBrushStretchUV.InitBrush (TiltBrush.BrushDescriptor desc, TiltBrush.TrTransform localPointerXf) (at Assets/Scripts/Brushes/QuadStripBrushStretchUV.cs:48)
TiltBrush.BaseBrushScript.Create (UnityEngine.Transform parent, TiltBrush.TrTransform xfInParentSpace, TiltBrush.BrushDescriptor desc, UnityEngine.Color color, System.Single size_PS) (at Assets/Scripts/Brushes/BaseBrushScript.cs:82)
TiltBrush.PointerScript.CreatePreviewLine () (at Assets/Scripts/PointerScript.cs:645)
TiltBrush.PointerScript.UpdatePointer () (at Assets/Scripts/PointerScript.cs:473)
TiltBrush.PointerManager.Update () (at Assets/Scripts/PointerManager.cs:505)
```

**Comment by billyquith** [comment]
Oh joy, now I'm getting an error on building Android,

```
_btb_ BuildPipeline.BuildPlayer() returned: "Errors:
Build player
  Building Player failed
Exporting project
  DirectoryNotFoundException: Could not find a part of the path "Temp\StagingArea\raw\Support\shaders\brushes\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43-v10.0-MainTex.png" or "C:\Code\Public\Builds\UnityXRMobile_Debug_OpenBrush_Il2cpp_FromGui\com.icosa.openbrush.apk\unityLibrary\src\main\assets\Support\shaders\brushes\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43-v10.0-MainTex.png""
UnityEngine.Debug:LogFormat (string,object[])
BuildTiltBrush:Note (string,object[]) (at Assets/Editor/BuildTiltBrush.cs:1683)
BuildTiltBrush:DoBuild (BuildTiltBrush/TiltBuildOptions) (at Assets/Editor/BuildTiltBrush.cs:1408)
BuildTiltBrush:MenuItem_Build () (at Assets/Editor/BuildTiltBrush.cs:324)
TiltBrush.BuildWindow:<MakeBuildActionsGui>b__45_0 () (at Assets/Editor/BuildWindow.cs:421)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()
```

Initial guess: I think this is due to a filepath being too long. 🤦 

"C:\Code\Public\Builds\UnityXRMobile_Debug_OpenBrush_Il2cpp_FromGui\com.icosa.openbrush.apk\unityLibrary\src\main\assets\Support\shaders\brushes\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43\CoarseBristles-1161af82-50cf-47db-9706-0c3576d43c43-v10.0-MainTex.png""

**Comment by mikeskydev** [comment]
> Initial guess: I think this is due to a filepath being too long. 🤦

I think this is the case, @PerlinWarp had a similar issue i think?

**Comment by mikeskydev** [comment]
![image](https://user-images.githubusercontent.com/9121007/154820665-47c445f4-6310-4261-b99a-8cf675b3207f.png)

ExportFbx relies on the vendor name being present in App.cs, which was changed in 234624f794a3d1816ffb66ed2ed6b798b62d2e6e. This will only be caught in editor if the `FBX_SUPPORTED` `FBXSDK_RUNTIME` defines are enabled.

**Comment by billyquith** [comment]
With current work UnityXR PC build appears to work, using Oculus XR plugin, and Oculus link works. However Android, builds, installs but does not display.

Getting this error spamming a lot:

    02-20 22:11:29.210  2036  2343 W Telemetry: [OpenXR] xrGetReferenceSpaceBoundsRect: unsupported reference space; 

[xrGetReferenceSpaceBoundsRect docs](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/xrGetReferenceSpaceBoundsRect.html). "The runtime must return XR_ERROR_REFERENCE_SPACE_UNSUPPORTED if the [XrReferenceSpaceType](https://www.khronos.org/registry/OpenXR/specs/1.0/man/html/XrReferenceSpaceType.html) passed in createInfo is not supported by this session."

**Comment by billyquith** [comment]
This mostly seems to be working now. The final issue, and why the launch intent wasn't found was that the package name was wrong. Unity appends "unityeditor" to the name. This is fixed in the branch. You can use `apkanalyser manifest print` to see the manifest used in the APK.

**Comment by billyquith** [comment]
@mikeage is having issues with Oculus spatializer building for CI. Need a repro.

**Comment by merulaxr** [comment]
We discovered TB didn't use the Oculus Spatializer as the README didn't specify importing it for builds.

**Comment by merulaxr** [comment]
@billyquith Do you feel this is in a good place to close out w.r.t compatibility on quest 2? I feel other android headsets deserve their own issues to track, but this should be fairly stable on quest now.
