### ISSUE TITLE
Saving issue on Quest 2 for newer Android SDK versions

### ISSUE THREAD

**Issue by mikeskydev** [icosa-gallery/open-brush#23]
We previously attempted to upgrade the target Android SDK to version 29, as this was the minimum targeted version shipped with Unity 2019.4.18. However this created an issue with saving on Quest 2, where it does not have the correct permissions to access the  Open Brush/Tilt Brush folder due to an implementation change on higher Android SDKs. 

A temporary fix was proposed in #18 using a legacy option in the android manifest file, but I feel we should take the time to implement it correctly instead, as this fix is already obsolete in the latest version of the Android SDK.

**Comment by billyquith** [comment]
Notes on possible fix: https://stackoverflow.com/questions/63842070/accessing-external-storage-in-android-api-29

**Comment by mikeage** [comment]
I realize that targeting Android 30 will require a different fix, but can we revisit the proposal of #18? Unity 2019.4.18f ships with an Android SDK of 29, and I think that the value of being able to build with that version (without needing to install Android Studio and the SDK for 26) exceeds the value of keeping the original TB code (which was, in any case, Unity 2018) or the value of avoiding deprecated code in a version where it's still the "proper" fix.

**Comment by mikeskydev** [comment]
After research, it looks like Unity doesn't have a native way to access the new scoped permissions system in newer Android SDKs as of yet, and there's no clear timeline for this being available. I concur with @mikeage that for compatibility's sake it would be better applying #18 until if and when Unity is ready. This will also help with #43 when it's ready!

**Comment by mikeage** [comment]
So #43 is actually ready, just blocked on:
* this
* One open design question (license as Github secret or in the file
* Actually setting up the license, which needs another branch
But it's ready :-)

**Comment by mikeskydev** [comment]
Fix provided in #49, Will close this for now and revisit when better options are available in Unity.
