### ISSUE TITLE
Clean install on up-to-date Quest 2 crashes on start up

### ISSUE THREAD

**Issue by DoctorMikeReddy** [icosa-gallery/open-brush#231]
I’ve just installed Open Brush on Quest 2 and it constantly crashes on start up

**Comment by DoctorMikeReddy** [comment]
Installed via App Lab

**Comment by andybak** [comment]
We can't reproduce this and as far as I'm aware nobody else has reported it. I know that's not very comforting for you but it's hard to know how to progress this.

**Comment by DoctorMikeReddy** [comment]
My bad - although not my fault, directly - as this was an Oculus for Business Quest 2 headset, but hadn't been commisioned for that special (and very restricted) OS. Therefore, it wouldn't update past v29 firmware (as it wasn't on the list of 'commercial' devices). As O4B is being discontinued now, all these Q2s have been redesignated as normal headsets, and can now be updated. Open Brush now works fine, thankfully.
