### ISSUE TITLE
Google login  for PC version

### ISSUE THREAD

**Issue by DoctorMikeReddy** [icosa-gallery/open-brush#232]
There's an option to log in with Google to access YouTube, etc, in the Accounts tab. However, Google blocks login in the browser. Is this broken, or now non-fuctional? Using latest version; I tried the Steam and the Oculus PC versions

**Comment by DoctorMikeReddy** [comment]
Just an update, now that I have OB for Quest running - see #231 - it does allow Google log in. So, it appears to only be the PCVR affected

**Comment by merulaxr** [comment]
![image](https://user-images.githubusercontent.com/9121007/161434381-4f6e908c-2634-4cb5-8e84-c96dd749da21.png)

PCVR-only confirmed, Open Brush is submitting a request for YouTube related API scopes, which has been moved to a restricted scope by Google requiring reverification. Reasoning and proof has been submitted

**Comment by merulaxr** [comment]
@DoctorMikeReddy this has been temporarily resolved by removing the YouTube related scopes. We hope to add these back in when Google approves us.
