### ISSUE TITLE
Unity XR Validation

### ISSUE THREAD

**Issue by merulaxr** [icosa-gallery/open-brush#249]
WIP Checklist to validate all functions and permutations of Open Brush in the `xr_v2` branch before we consider merging.

#237

## Platform Support
Basic test, can we build and run on this platform that was supported previously?
- [x] Windows SteamVR - now delivered via generic Windows OpenXR
- [x] Oculus Rift
- [x] Oculus Quest
- [x] Vive Desktop (Same as Windows SteamVR for now)

## Controller schemes
Check that inputs are valid and controllers act correctly
- [x] Vive wands
- [x] Valve Index (Knuckles)
- [x] Oculus Rift
- [x] Oculus Quest (also via Link)
- [ ] WMR

## Panels
Note that a lot of panels have a 'Mobile' version that may behave differently. 

- [x] Admin Panel
- [x] Admin Panel Mobile
- [x] App Settings
- [x] App Settings Mobile
- [x] Brush Picker
- [x] Brush Mobile
- [x] Camera
- [x] Camera Path
- [x] Color Picker
- [x] Environment
- [x] Extra Panel
- [x] Extra Panel Mobile
- [x] Guides
- [x] Labs
- [x] Labs Mobile
- [x] Layers
- [x] Lights
- [ ] Memory Warning
- [x] Reference
- [x] Reference Mobile
- [x] Scripts
- [x] Sketchbook
- [x] Sketchbook Mobile
- [x] Snap Settings
- [x] Tools Basic
- [x] Tools Basic Mobile
- [x] Tools Advanced
- [x] Tools Advanced Mobile
- [x] Tutorials

## Minor
Things that may or may not work, but shouldn't prevent release.

### Platforms
- [x] Windows SteamVR Experimental
- [ ] Windows Monoscopic Experimental (Minor) We may need to reconsider supporting this mode temporarily with the move to UnityXR. It's not a primary release method and I don't want it to hold up main platforms.
- [x] Oculus Rift Experimental
- [x] Oculus Quest Experimental
- [ ] Linux SteamVR - may best be supported through Proton
- [ ] Linux SteamVR Experimental - may best be supported through Proton
- [ ] Linux Monoscopic (Minor)
- [ ] macOS Monoscopic (Minor)

### Controller schemes
- [ ] Vive Cosmos (There's prefabs for this, but they look rather unfinished.)
- [ ] Logitech Pen (Minor)

### Panels
- [x] Brush Experimental (Minor)
- [x] Experimental (Minor)
- [x] Poly (Deprecated)
- [x] Poly Mobile (Deprecated)

**Comment by andybak** [comment]
Monoscopic is pretty essential for me while developing so I might have to have a look at that. (Seriously - do you all keep taking a damn headset on and off while you're working on Open Brush? Drives me mad - I try and do 80% of my dev without needing a headset.

**Comment by merulaxr** [comment]
Valid for developers, sure! I've altered the previous VrSdk mode to be OfflineMode for now, which should retain Mono compatibility in editor for development.

**Comment by mikeage** [comment]
Should we build a release in monoscopic mode, or assume it's only used in the editor?

**Comment by andybak** [comment]
Personally I only use it in the editor at the moment but I have some ideas to use it for a viewer app and other things that might require a build.

**Comment by merulaxr** [comment]
If you're happy to keep using that, post-merge I'd like to look at making mono mode a proper member of the desktop builds that can be switched between.

**Comment by merulaxr** [comment]
From 松田浩二#7263 in Discord: https://discord.com/channels/783806589991780412/806934697237938216/995929974219481088

>Yesterday, I tried a little beta version of the XR.
When I used the delayed input, the brush movement speed became extremely slow compared to the previous version. Is this a specification?

This is related to the lazy input tool, which is Open Brush specific. The trigger value passing may have changed during the XR upgrade.

**Comment by hiinaspace** [comment]
I tried out the xr branch a bit on windows 10 / steamVR / valve index. The triggers in the menu seem to double-tap or otherwise prevent some of the sub-menus from appearing unless you're very gentle on the trigger or use an odd angle. video: https://streamable.com/4sxvyc

**Comment by merulaxr** [comment]
@hiinaspace thanks! I'd picked up on this too, I know where I introduced it so I should have it fixed sometime tomorrow. Thanks for the report!

**Comment by andybak** [comment]
Experimental brushes are still disabled. (the bit that adds them to the manifest in GetMergedManifest is commented out)

https://github.com/icosa-gallery/open-brush/commit/fdeb7ce4689be572a150edeeb5f159a5679aef6c

https://discord.com/channels/783806589991780412/936208281804890193/997871247327248474

**Comment by merulaxr** [comment]
Thanks, I'd picked up on that while messing around but didn't realise what caused it. Fixed!

**Comment by merulaxr** [comment]
App settings mobile and Extras panel mobile both have issues on Quest. Camera tool is broken, and contribute button doesn't work.

**Comment by merulaxr** [comment]
Tutorial cube is missing controllers

**Comment by merulaxr** [comment]
Sketch cost appears to be broken at least on mobile, meaning memory warning never shows

**Comment by merulaxr** [comment]
Lack of compositor on desktop makes exporting/loading large scenes quite nauseous!
