### ISSUE TITLE
Save icon snapshot is not attached to brush

### ISSUE THREAD

**Issue by chengnay** [icosa-gallery/open-brush#265]
After clicking "Save Sketch", the snap shot frame(yellow box in below image) stays floating in the air.
![image](https://user-images.githubusercontent.com/33050705/180737118-011c711e-96e7-4944-a049-c9095b967ec8.png)

I found out in SaveIconTool.cs, LateUpdateTool function is not called.
Not sure if this is the root cause.

**Comment by merulaxr** [comment]
Hi! Is this in the XR beta?

**Comment by chengnay** [comment]
I am using feature/xr_v2 branch.

**Comment by merulaxr** [comment]
Thanks, I have a feeling I know where this is coming from, it's on my fix list for today/tomorrow. Thanks for submitting!

I believe this is from the Mobile Bloom script attached to the mono camera used to take the snapshots. Something changed between 2019 and 2021 that breaks how this functions for mono cameras compared to the stereo camera used for the HMD.

**Comment by merulaxr** [comment]
Fixed on xr_v2 #237 in 7f3e6a4c98c2e8985d5a55cdc429219a32615d59
