### ISSUE TITLE
Lots of TMPro NullReferenceException

### ISSUE THREAD

**Issue by chengnay** [icosa-gallery/open-brush#270]
I was developing on feature/xr_v2 branch, and I see lots of TMPro NullReferenceException in log.
How should I resolve it? Thanks!

`08-03 09:29:32.860 13556 13579 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
08-03 09:29:32.860 13556 13579 E Unity   :   at TMPro.TMP_Settings.get_fallbackFontAssets () [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at TMPro.TMP_Text.GetEllipsisSpecialCharacter (TMPro.TMP_FontAsset fontAsset) [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at TMPro.TMP_Text.GetSpecialCharacters (TMPro.TMP_FontAsset fontAsset) [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at TMPro.TextMeshPro.LoadFontAsset () [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at TMPro.TextMeshPro.Awake () [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at UnityEngine.Object.Instantiate[T] (T original) [0x00000] in <00000000000000000000000000000000>:0 
08-03 09:29:32.860 13556 13579 E Unity   :   at TiltBrush.SketchControlsScript.Start () [0x00000] in <00000000000000000000000000000000>:0 `

**Comment by merulaxr** [comment]
Just want to check, have you imported the Text Mesh Pro Essential resources? https://learn.unity.com/tutorial/textmesh-pro-importing-the-package

**Comment by chengnay** [comment]
@merulaxr Thanks, I think I miss that part. :)
