### ISSUE TITLE
Support for Pico standalone headsets

### ISSUE THREAD

**Issue by uramer** [icosa-gallery/open-brush#302]
It shouldn't be much different from supporting Oculus Quest in concept. You can find the documentation here https://developer-global.pico-interactive.com/document/OpenXR

I might be interested in making a PR for this. Any pointers on where to start?

**Comment by merulaxr** [comment]
Hi, and thanks for the suggestion! We are already working with Pico and have a PR open for this, which should hopefully be merged in the next few weeks pending approval from QA. Thanks!

**Comment by uramer** [comment]
Ah, nice! I did search the issues, but didn't think to look at PRs as well.
