### ISSUE TITLE
HP Reverb Controlers problem

### ISSUE THREAD

**Issue by pietru2004** [icosa-gallery/open-brush#399]
Hello I have noticed that HP Reverb controllers don't have binds for undo/redo in advanced mode
Menu button also seams to have no bindings.

![20230112_090159.jpg](https://user-images.githubusercontent.com/51274570/212011332-314d2a52-57ac-49cf-bb5e-5b4165dbf43f.jpg)

**Comment by mikeskydev** [comment]
Hi, is this using the latest beta (2.0.15) that provides proper support for the WMR controllers?

**Comment by pietru2004** [comment]
it is on steam stable - I did not turn on beta of app

**Comment by pietru2004** [comment]
I checked beta and it works...

**Comment by mikeskydev** [comment]
Thanks for checking! We hope to release 2.1 as a hotfix, which will include this fix for your controllers very shortly. Apologies for the temporary inconvenience!
