### ISSUE TITLE
Wrong caption for the "enable experimental mode" hover text

### ISSUE THREAD

**Issue by mikeage** [icosa-gallery/open-brush#405]
It looks like it took part of the text from the measuring option:

!["on straightedge tool"](https://user-images.githubusercontent.com/87874/219591902-5413fc0f-7756-4b23-9d6f-00ef6999ee6b.jpeg)

**Comment by mikeage** [comment]
I actually noticed it in 2.0 and kept forgetting to look up how to take a screenshot... or even remembering what the exact text was :-)

**Comment by mikeskydev** [comment]
Fixed in #412
