### ISSUE TITLE
The Collider OnTriggerEnter() function doesn't work when the Openbrush runs.

### ISSUE THREAD

**Issue by cz2011301070** [icosa-gallery/open-brush#411]
In the same Openbrush project, if I created and new scene, and created two cubes and correctly set the collision detection components.
If I run the scene, and drag one the cubes to collide another, The OnTriggerEnter() function works normally.
However, If I copy the two cubes into Main scene where OpenBrush config is used, the OntriggerEnter() function made no response.

**Comment by mikeskydev** [comment]
For performance reasons, the main open brush scene disables physics entirely because we don't use it! If you want to turn it back on, I think it's either in App.cs or Config.cs.

**Comment by cz2011301070** [comment]
Thanks for letting me know. 

I am using the OpenBrush in a study which uses the collider to detect when to enable drawing. 

I found the code is in App.cs locating at the beginning of Awake()

**Comment by mikeskydev** [comment]
Nice, we'd be very interested in hearing more about the process and results of the study when you're done!
