### ISSUE TITLE
"OpenBrush" Monoscopic for Mac is Damaged

### ISSUE THREAD

**Issue by 23dogsinatrenchcoat** [icosa-gallery/open-brush#425]
I am trying to run OpenBrush Monoscopic for Mac, but no matter what I try (and I've tried everything websites say to do with damaged files), I get the error message: "“OpenBrush” is damaged and can’t be opened. You should move it to the Trash." I've even tried downloading WineBottler and opening the Windows Monoscopic version, but no luck there either. Does anyone know how to fix the damaged file or something? I'd really love to playa around with this. Thanks!

**Comment by mikeage** [comment]
Hi, based on the discussion on Discord, it seems that the path to `xattr` was incorrect. If you're still having issues, please feel free to re-open.
