### ISSUE TITLE
Color Wheel UI page disappeared in Advanced Mode

### ISSUE THREAD

**Issue by SebastianVRLab** [icosa-gallery/open-brush#434]
Hi,
I had a really great experience after installing Open Brush on Win10 and using it with the Quest 2.
However, after a few hours of usage the color pcker UI disappeared in the advanced user mode. The whole page is missing and the place where the UI box used to be is just blank now.

When switching to the Beginner mode, the page appears again. 

Uninstalled Open Brush from Steam VR, removed it from the library, wiped the local folders on my PC, restarted PC. Unfortunately without success.

Does anyone have an idea how to resolve this problem?
Thanks in advance!!

Using it with Nvidia RTX3070 and Oculus Air Link via Steam. Problem persists with Oculus Link on Cable.

**Comment by mikeskydev** [comment]
Hi! Glad you've been enjoying Open Brush so far!

Advanced mode allows users to grab panels from their palette to re-arrange however you want, including leaving them floating in a fixed space. It sounds like at some point you may have accidentally pulled the color picker off the palette and flung it somewhere out of sight? 

Regardless, you can quickly and easily try resetting the panel positions. On your radial menu, select 'more options' 
![image](https://user-images.githubusercontent.com/9121007/234797160-52090fb5-e382-4ac9-a550-606283a520b0.png)
Then there is an option to 'reset panels' in the bottom right. 
![image](https://user-images.githubusercontent.com/9121007/234797226-4c2777cb-63ed-4c71-8a11-ade921de802d.png)

Let me know if that works! Thanks

**Comment by SebastianVRLab** [comment]
Hi Mike, thanks so much for your quick reply and the effort to attach the screenshots.
Awesome, that solved the issue indeed!! (I assume another user must have pulled it off during a model check..)

Keep up the great work with OpenBrush! 
Best, Sebastian

**Comment by mikeskydev** [comment]
Nice, glad to hear that solved it and it was a quick fix!
