### ISSUE TITLE
After click sign in for Google, nothing happen

### ISSUE THREAD

**Issue by chengnay** [icosa-gallery/open-brush#443]
I found out that do the following steps,
1. Click Accounts
2. Sign in for Google
3. Save and proceed
4. Nothing happen

Did I miss anything here?
I use platform/wave branch.

**Comment by mikeskydev** [comment]
You will need our specific API keys to open the sign in process, see the README on how to generate your own for testing. 

However, HTC appear to have an OS-level issue with keeping the app running in the background so at this moment sign-in won't work on at least the XR Elite. We're working with HTC on this.
