### ISSUE TITLE
Cannot record camera paths

### ISSUE THREAD

**Issue by mikeskydev** [icosa-gallery/open-brush#47]
Steps to reproduce:
- Select the camera path tool
- Draw a camera path
- press the record button

Expected result: Your camera path plays back and records
Actual result: Nothing happens

**Comment by Scenarman** [comment]
Hello, I agree, it's a big problem for the artists to expose them sculptures on vidéos (Insta, FaceBook). I continue on Tiltbrush for now... :(
Thanks

**Comment by mikeskydev** [comment]
Perhaps we should read the README... https://github.com/icosa-gallery/open-brush#camera-path-support this appears to fix the issue 😅
