### ISSUE TITLE
SketchFab Uploads from open brush as tilt brush. 

### ISSUE THREAD

**Issue by PerlinWarp** [icosa-gallery/open-brush#50]
![SketchFab](https://user-images.githubusercontent.com/15193605/109394441-eac9b700-791e-11eb-8ba0-54fceed29d42.png)

Inside the CreateModel() in `Assets/Scripts/Sharing/SketchfabService.cs`, we can also pass an openbrush tag, and change the service to openbrush, not sure how we would change the logo yet.

**Comment by PerlinWarp** [comment]
LGTM! 

![image](https://user-images.githubusercontent.com/15193605/113939097-70306900-97f3-11eb-9272-a2269392e16d.png)

Sample uploads have been changed, see [here](https://sketchfab.com/3d-models/open-brush-upload-from-quest-test-a70eb58a0db74d1bb19db04110bedfd5). 

We are also now added to their exporters, see [here](https://sketchfab.com/exporters). 
![image](https://user-images.githubusercontent.com/15193605/113939279-b38ad780-97f3-11eb-9dd5-c976427fd402.png)

**Comment by mikeskydev** [comment]
Thanks, looks great!
