### ISSUE TITLE
Reference Library models import tab is missing.

### ISSUE THREAD

**Issue by TimAidley** [icosa-gallery/open-brush#53]
From a [user report](https://discord.com/channels/783806589991780412/804251629993197618/818520140336463912) on discord:

> **Noartnoglory**
> Hello amazing devs! I had a question. I understand .fbx import is not supported in Open Brush but I was wondering why this option was removed completely from the current version? I only ask because I have been experimenting with creating singular models that I can use repeatedly in scenes. I know it's different software but I am able to import .gbl files from TIlt/OpenBrush into Multibrush via my PC. Do you think this option to import models will arrive in the future? Maybe not .fbx but potentially .gbl?
> 
> **Mikesky**
> Removed completely? How so? We added fbx export support in open brush 0.2.0, and I wasn’t even aware that you could import fbx on original tilt brush. Could tilt brush desktop import glb? We can do that most likely
> 
> **Noartnoglory**
> Hey @Mikesky , I should have used better choice of words. Within the Media Library section the icon for selecting model is gone. It is blank and only shows icons for image and video. I am able to import .glb exports from Open Brush into PC version of Tilt Brush by dragging/dropping the .glb into the Tilt Brush Media Library model folder.

**Comment by andybak** [comment]
Closing this because as far as I can tell 3d model import was intentionally disabled on the Quest. (or rather - never enabled)

**Comment by mikeskydev** [comment]
This was originally in experimental mode, but has now been moved to public as of 2.0.
