### ISSUE TITLE
Quest 1 Crashing

### ISSUE THREAD

**Issue by PerlinWarp** [icosa-gallery/open-brush#62]
**Origins of the strange crashing:**
We have received an app lab review mentioning "I only wish I could spend more than 5 minutes without it completely crashing on me"

Siiimon from the Discord, also came across this bug on a Quest 1: "Hi. I am testing open brush on quest via app lab (v 0.2.0), but it seems to crash every few minutes."

Personally, I have been unable to find any crashing on the Quest 2, but did get a logcat of a crash from my Quest 1. 

**Logcat of a Crash**
Attached is a crash log, you can see the crash happens just before 23:03:43
[logcat23-04crash.log](https://github.com/icosa-gallery/open-brush/files/6167769/logcat23-04crash.log)

`2021-03-18T23:03:43.519Z:error14408/14377 AndroidRuntime
FATAL EXCEPTION: UnityMain<br>Process: com.Icosa.OpenBrush, PID: 14377<br>java.lang.Error: FATAL EXCEPTION [UnityMain]<br>Unity version     : 2019.4.18f1`

**Possible Reproduction of the crash**
@mikeskydev got a crash on scene change. 
To reproduce this, I kept opening many different scenes with varying complexities and also spent time drawing in new scenes. 
Of the 4 times, I have managed to get a crash. 3 were while loading scenes, and 1 happened after taking the headset on and off after loading a scene, which is the one in the logcat, note the `onHeadsetMounted`. 

Once a crash has happened I have been unable to get another until I reinstall Open Brush. 
**If anyone know how to get a crash, please comment here.**

**Comment by PerlinWarp** [comment]
Update, in the logcats are complaints about "https://lh3.goog..." which we assume is "https://lh3.googleusercontent.com/". As @mikeskydev pointed out, this is where Poly thumbnails are stored.

The Multibrush creator, TeddyCatsDomino, also had these issues inside of MultiBrush and found that after removing the Google credentials from the Secrets asset, the app no longer crashes.

**Comment by PerlinWarp** [comment]
Due to the fast approaching end of Poly, we decided it is not worth our time to get this working and a **quick patch would be to just disable Poly integration.** 

This is not as simple as removing the API key from secrets as we do want to support other Google features. 

I will close this issue when we have disabled Poly integration.

**Comment by mikeskydev** [comment]
Disabled properly in #86
