### ISSUE TITLE
Vive Controllers not detected after SteamVR menu is closed (Linux)

### ISSUE THREAD

**Issue by tuxfoo** [icosa-gallery/open-brush#67]
Hello,

I have built this for Linux. 
In order for Open-Brush to detect my Vive Controllers I have to close any steamvr menu's before launching Open-Brush. While Open-Brush is running I then need to make sure not to hit the home button because exiting the steamVR overlay menu results in Open-Brush not detecting the controllers again.

Regards, tuxfoo.

**Comment by merulaxr** [comment]
As we've moved away from SteamVR to OpenXR we won't be fixing this issue. We're pushing Unity hard to support building OpenXR natively to Linux. Sorry for the inconvenience. I'd love to know if our OpenXR build functions through Proton if anyone is able to test.
