### ISSUE TITLE
Crash on "Enable Profiling"

### ISSUE THREAD

**Issue by b-camacho** [icosa-gallery/open-brush#7]
Thanks for all the great work, can't wait to open some PRs!

Build:
9d84ab023b48f67d261adc9294fe9a560f05f21b

Platform:
SteamVR (Valve Index)
Windows 10 Home Edition, x86-64 

Repro steps:
1. Enable "advanced mode"
2. From the top left hand menu, select "enable profiling"
3. Select "enable profiling" again
4. App freezes

I'll try and figure out why this happens, but leaving this here in case I don't find anything

**Comment by mikeskydev** [comment]
Fixed in #8
