### ISSUE TITLE
Building for Android IL2CPP fails

### ISSUE THREAD

**Issue by mikeskydev** [icosa-gallery/open-brush#87]
Oculus reccommend targeting arm64 for Quest builds, and suggest they might block arm7 in the future. I've previously tested this when submitting to app lab and some errors, which I think are coming from third party libraries.

**Comment by mikeskydev** [comment]
Build error output:

```
ArgumentException: The Assembly ICSharpCode.SharpZipLib is referenced by Pngcs ('Assets/ThirdParty/pngcs/Pngcs.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <afa5b9a1793446ff98b741dc036c4c6e>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <afa5b9a1793446ff98b741dc036c4c6e>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <afa5b9a1793446ff98b741dc036c4c6e>:0)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
BuildTiltBrush:DoBuild(TiltBuildOptions) (at Assets/Editor/BuildTiltBrush.cs:1158)
BuildTiltBrush:MenuItem_Build() (at Assets/Editor/BuildTiltBrush.cs:281)
TiltBrush.BuildWindow:<MakeBuildsGui>b__38_0() (at Assets/Editor/BuildWindow.cs:332)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**Comment by mikeskydev** [comment]
https://github.com/icosa-gallery/open-brush/blob/8ca2f95c52fd9c61d0d5e871c81186f9247d90af/Assets/ThirdParty/SharpZipLib/README.tiltbrush#L1-L3

Is this officially @dubois 's one to solve? 😉 I'll clone upstream and see if we need to build a new version.

**Comment by mikeskydev** [comment]
I was able to get a successful build after updating Pngcs to a newer version. I need to work out what this actually affects and do some testing before calling this fixed.

**Comment by dubois** [comment]
Hmm. The issue may be that the prebuilt .dll in the TB repo was built against a really ancient version of .net?

There's not much different in that repo vs upstream, just a giant performance fix that shows up in Mono. It's entirely likely that in the intervening 6 years (!) it's been fixed. And also Unity's changed its .net implementation and so on. If .tilt files continue to load quickly, then using plain upstream is probably fine!
